XGBRegressor:
  objective: reg:squarederror
  booster: gbtree
  n_estimators: 100
  learning_rate: 0.3
  max_depth: 6
  min_child_weight: 1
  gamma: 0.0
  subsample: 0.8
  colsample_bytree: 1.0
  reg_alpha: 0
  reg_lambda: 1
  random_state: 42
  scale_pos_weight: 1


