artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion 
  mongo_uri: mongodb+srv://Minich:Mydatabase.456@minich-data-repository.gzlkk1s.mongodb.net/
  database_name: battery_experiments
  collection_name: battery_rul


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/battery_rul.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/battery_rul.csv
  numerical_cols:
    - 'cycle_index'            
    - 'discharge_time_s'       
    - 'decrement_3_6_3_4v_s'   
    - 'max_voltage_discharge_v'
    - 'min_voltage_charge_v'   
    - 'time_at_4_15v_s'        
    - 'time_constant_current_s'
    - 'charging_time_s'       
                 
  categorical_cols: []

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts\data_transformation\ X_train_transformed.joblib
  test_data_path: artifacts\data_transformation\X_test_transformed.joblib
  #y_train_data_path: artifacts/data_transformation/y_train_arr.npy
  #y_test_data_path: artifacts/data_transformation/y_test_arr.npy
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/X_test_transformed.joblib
  test_target_variable: artifacts/data_transformation/y_test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json


performance_validation:
  root_dir: artifacts/validation_results
  metric_file_name: artifacts/model_evaluation/metrics.json
  validation_status_file: artifacts/validation_results/validation_status.json





  
